### PR TITLE
Decode Turkish text from ISO-8859-9

### PR DESCRIPTION
**Pull request by bcaller**
This should fix your pull request at https://github.com/eskerda/pybikes/pull/187

### CODE REVIEW

**Comment by anastmag** [comment]
Check the following:

`import pybikes`
`a=pybikes.get('baksi-bisim')`
`a.update()`
`print a.stations[0]`

does it print the first line correctly ?

**Comment by bcaller** [comment]
Yes, `\u0130nciralt\u0131 Rekreasyon Alan\u0131` is correct unicode for `İnciraltı Rekreasyon Alanı`

**Comment by bcaller** [comment]
Try for example `pybikes.get('velobike-moscow')` to see how Cyrillic characters are shown.
When printed out in the JSON in the API they will be displayed as you want e.g. https://api.citybik.es/v2/networks/velobike-moscow.

**Comment by anastmag** [comment]
Alright it's in unicode but was it supposed to be printed as unicode and not as Cyrillic ?

**Comment by anastmag** [comment]
I just discovered that in citybik.es they are printed in Cyrillic. I was trying to return them in Turkish alphabet.

**Comment by anastmag** [comment]
You are right bcaller. Thanks

**Comment by bcaller** [comment]
You're welcome. The problem is perhaps that on Windows, Python cannot print Unicode characters properly to the console. JSON will be fine.

**Comment by anastmag** [comment]
No i'm running Debian. I managed to convert them to unicode (although not the html_data variable, but lower the BaksiStation.name variable) but i was trying to have the Turkish characters properly printed in console. I didn't know this detail about json and the API. Thanks again

**Pull request merged**
